// <auto-generated />
using System;
using FitManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FitManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260421000000_AddClassesModule")]
    partial class AddClassesModule
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FitManager.Models.FitnessClass", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<int>("Category").HasColumnType("int");
                b.Property<string>("InstructorName").IsRequired().HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("Location").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("Color").IsRequired().HasMaxLength(7).HasColumnType("varchar(7)");
                b.Property<DateTime>("StartDate").HasColumnType("datetime(6)");
                b.Property<DateTime?>("EndDate").HasColumnType("datetime(6)");
                b.Property<int?>("MaxCapacity").HasColumnType("int");
                b.Property<bool>("IsActive").HasColumnType("tinyint(1)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("CreatedBy").HasMaxLength(256).HasColumnType("varchar(256)");
                b.HasKey("Id");
                b.ToTable("FitnessClasses");
            });

            modelBuilder.Entity("FitManager.Models.ClassSchedule", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("FitnessClassId").HasColumnType("int");
                b.Property<int>("ScheduleType").HasColumnType("int");
                b.Property<int>("DaysOfWeek").HasColumnType("int");
                b.Property<int?>("DayOfMonth").HasColumnType("int");
                b.Property<DateTime?>("SpecificDate").HasColumnType("datetime(6)");
                b.Property<TimeSpan>("StartTime").HasColumnType("time(6)");
                b.Property<TimeSpan>("EndTime").HasColumnType("time(6)");
                b.Property<DateTime>("EffectiveFrom").HasColumnType("datetime(6)");
                b.Property<DateTime?>("EffectiveTo").HasColumnType("datetime(6)");
                b.Property<bool>("IsActive").HasColumnType("tinyint(1)");
                b.Property<string>("Notes").HasMaxLength(300).HasColumnType("varchar(300)");
                b.HasKey("Id");
                b.HasIndex("FitnessClassId");
                b.ToTable("ClassSchedules");
            });

            modelBuilder.Entity("FitManager.Models.ClassEnrollment", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("FitnessClassId").HasColumnType("int");
                b.Property<int>("MemberId").HasColumnType("int");
                b.Property<DateTime>("EnrolledAt").HasColumnType("datetime(6)");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("EnrolledBy").HasMaxLength(256).HasColumnType("varchar(256)");
                b.HasKey("Id");
                b.HasIndex("FitnessClassId", "MemberId");
                b.HasIndex("MemberId");
                b.ToTable("ClassEnrollments");
            });

            modelBuilder.Entity("FitManager.Models.ClassSchedule", b =>
            {
                b.HasOne("FitManager.Models.FitnessClass", "FitnessClass")
                 .WithMany("Schedules")
                 .HasForeignKey("FitnessClassId")
                 .OnDelete(DeleteBehavior.Cascade)
                 .IsRequired();
                b.Navigation("FitnessClass");
            });

            modelBuilder.Entity("FitManager.Models.ClassEnrollment", b =>
            {
                b.HasOne("FitManager.Models.FitnessClass", "FitnessClass")
                 .WithMany("Enrollments")
                 .HasForeignKey("FitnessClassId")
                 .OnDelete(DeleteBehavior.Cascade)
                 .IsRequired();
                b.HasOne("FitManager.Models.Member", "Member")
                 .WithMany()
                 .HasForeignKey("MemberId")
                 .OnDelete(DeleteBehavior.Restrict)
                 .IsRequired();
                b.Navigation("FitnessClass");
                b.Navigation("Member");
            });

            modelBuilder.Entity("FitManager.Models.FitnessClass", b =>
            {
                b.Navigation("Schedules");
                b.Navigation("Enrollments");
            });
#pragma warning restore 612, 618
        }
    }
}
