// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FitManager.Migrations
{
    [DbContext(typeof(FitManager.Data.ApplicationDbContext))]
    [Migration("20260503000000_AddWhatsAppSettings")]
    partial class AddWhatsAppSettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
