// <auto-generated />
using System;
using FitManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FitManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260103000000_AddCashRegisterReopen")]
    partial class AddCashRegisterReopen
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FitManager.Models.CashRegister", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<DateTime>("Date").HasColumnType("datetime(6)");
                b.Property<decimal>("OpeningBalance").HasColumnType("decimal(10,2)");
                b.Property<decimal?>("ClosingBalance").HasColumnType("decimal(10,2)");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<string>("OpenedBy").IsRequired().HasMaxLength(256).HasColumnType("varchar(256)");
                b.Property<string>("ClosedBy").HasMaxLength(256).HasColumnType("varchar(256)");
                b.Property<DateTime>("OpenedAt").HasColumnType("datetime(6)");
                b.Property<DateTime?>("ClosedAt").HasColumnType("datetime(6)");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<bool>("WasReopened").HasColumnType("tinyint(1)");
                b.Property<string>("ReopenedBy").HasMaxLength(256).HasColumnType("varchar(256)");
                b.Property<DateTime?>("ReopenedAt").HasColumnType("datetime(6)");
                b.Property<string>("ReopenNotes").HasMaxLength(500).HasColumnType("varchar(500)");
                b.HasKey("Id");
                b.HasIndex("Date").IsUnique();
                b.ToTable("CashRegisters");
            });
#pragma warning restore 612, 618
        }
    }
}
