// <auto-generated />
using System;
using FitManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FitManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260423000000_AddCompanySettings")]
    partial class AddCompanySettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FitManager.Models.CompanySettings", b =>
            {
                b.Property<int>("Id").HasColumnType("int");
                b.Property<string>("Name").IsRequired().HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("Slogan").HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<string>("LogoPath").HasMaxLength(300).HasColumnType("varchar(300)");
                b.Property<string>("Address").HasMaxLength(250).HasColumnType("varchar(250)");
                b.Property<string>("City").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("Province").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("Country").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("TaxId").HasMaxLength(30).HasColumnType("varchar(30)");
                b.Property<string>("Phone").HasMaxLength(30).HasColumnType("varchar(30)");
                b.Property<string>("Phone2").HasMaxLength(30).HasColumnType("varchar(30)");
                b.Property<string>("Email").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("Website").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime(6)");
                b.HasKey("Id");
                b.ToTable("CompanySettings");
            });
#pragma warning restore 612, 618
        }
    }
}
