// <auto-generated />
using System;
using FitManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FitManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260421010000_AddClassCategories")]
    partial class AddClassCategories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FitManager.Models.ClassCategory", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("Description").HasMaxLength(300).HasColumnType("varchar(300)");
                b.Property<string>("Color").IsRequired().HasMaxLength(7).HasColumnType("varchar(7)");
                b.Property<string>("Icon").IsRequired().HasMaxLength(60).HasColumnType("varchar(60)");
                b.Property<int>("OrderIndex").HasColumnType("int");
                b.Property<bool>("IsActive").HasColumnType("tinyint(1)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.HasKey("Id");
                b.HasIndex("Name").IsUnique();
                b.ToTable("ClassCategories");
            });

            modelBuilder.Entity("FitManager.Models.FitnessClass", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<int?>("ClassCategoryId").HasColumnType("int");
                b.Property<string>("InstructorName").IsRequired().HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("Location").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("Color").IsRequired().HasMaxLength(7).HasColumnType("varchar(7)");
                b.Property<DateTime>("StartDate").HasColumnType("datetime(6)");
                b.Property<DateTime?>("EndDate").HasColumnType("datetime(6)");
                b.Property<int?>("MaxCapacity").HasColumnType("int");
                b.Property<bool>("IsActive").HasColumnType("tinyint(1)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("CreatedBy").HasMaxLength(256).HasColumnType("varchar(256)");
                b.HasKey("Id");
                b.HasIndex("ClassCategoryId");
                b.ToTable("FitnessClasses");
            });

            modelBuilder.Entity("FitManager.Models.FitnessClass", b =>
            {
                b.HasOne("FitManager.Models.ClassCategory", "Category")
                 .WithMany("Classes")
                 .HasForeignKey("ClassCategoryId")
                 .OnDelete(DeleteBehavior.SetNull);
                b.Navigation("Category");
            });

            modelBuilder.Entity("FitManager.Models.ClassCategory", b =>
            {
                b.Navigation("Classes");
            });
#pragma warning restore 612, 618
        }
    }
}
