// <auto-generated />
using System;
using FitManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FitManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260102000000_AddPaymentModule")]
    partial class AddPaymentModule
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // ── Roles ─────────────────────────────────────────────────────────────
            modelBuilder.Entity("FitManager.Models.ApplicationRole", b =>
            {
                b.Property<string>("Id").HasColumnType("varchar(255)");
                b.Property<string>("ConcurrencyStamp").HasColumnType("longtext");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("Description").HasColumnType("longtext");
                b.Property<bool>("IsSystem").HasColumnType("tinyint(1)");
                b.Property<string>("Name").HasMaxLength(256).HasColumnType("varchar(256)");
                b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("varchar(256)");
                b.HasKey("Id");
                b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex");
                b.ToTable("Roles");
            });

            // ── Users ─────────────────────────────────────────────────────────────
            modelBuilder.Entity("FitManager.Models.ApplicationUser", b =>
            {
                b.Property<string>("Id").HasColumnType("varchar(255)");
                b.Property<int>("AccessFailedCount").HasColumnType("int");
                b.Property<string>("ConcurrencyStamp").HasColumnType("longtext");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("Email").HasMaxLength(256).HasColumnType("varchar(256)");
                b.Property<bool>("EmailConfirmed").HasColumnType("tinyint(1)");
                b.Property<string>("FirstName").IsRequired().HasColumnType("longtext");
                b.Property<bool>("IsActive").HasColumnType("tinyint(1)");
                b.Property<DateTime?>("LastLoginAt").HasColumnType("datetime(6)");
                b.Property<string>("LastName").IsRequired().HasColumnType("longtext");
                b.Property<bool>("LockoutEnabled").HasColumnType("tinyint(1)");
                b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("datetime(6)");
                b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("varchar(256)");
                b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("varchar(256)");
                b.Property<string>("PasswordHash").HasColumnType("longtext");
                b.Property<string>("PhoneNumber").HasColumnType("longtext");
                b.Property<bool>("PhoneNumberConfirmed").HasColumnType("tinyint(1)");
                b.Property<string>("PhotoPath").HasColumnType("longtext");
                b.Property<string>("SecurityStamp").HasColumnType("longtext");
                b.Property<bool>("TwoFactorEnabled").HasColumnType("tinyint(1)");
                b.Property<string>("UserName").HasMaxLength(256).HasColumnType("varchar(256)");
                b.HasKey("Id");
                b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex");
                b.ToTable("Users");
            });

            // ── Members ───────────────────────────────────────────────────────────
            modelBuilder.Entity("FitManager.Models.Member", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Address").HasMaxLength(300).HasColumnType("varchar(300)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("DNI").HasMaxLength(20).HasColumnType("varchar(20)");
                b.Property<DateTime?>("DateOfBirth").HasColumnType("datetime(6)");
                b.Property<string>("Email").HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("MemberNumber").IsRequired().HasMaxLength(20).HasColumnType("varchar(20)");
                b.Property<DateTime?>("MembershipEndDate").HasColumnType("datetime(6)");
                b.Property<DateTime>("MembershipStartDate").HasColumnType("datetime(6)");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("Phone").HasMaxLength(30).HasColumnType("varchar(30)");
                b.Property<string>("PhotoPath").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime(6)");
                b.HasKey("Id");
                b.HasIndex("DNI");
                b.HasIndex("MemberNumber").IsUnique();
                b.ToTable("Members");
            });

            // ── Plans ─────────────────────────────────────────────────────────────
            modelBuilder.Entity("FitManager.Models.Plan", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("Description").HasMaxLength(300).HasColumnType("varchar(300)");
                b.Property<decimal>("Price").HasColumnType("decimal(10,2)");
                b.Property<int>("PlanType").HasColumnType("int");
                b.Property<int>("DurationDays").HasColumnType("int");
                b.Property<bool>("IsActive").HasColumnType("tinyint(1)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.HasKey("Id");
                b.ToTable("Plans");
            });

            // ── CashRegisters ─────────────────────────────────────────────────────
            modelBuilder.Entity("FitManager.Models.CashRegister", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<DateTime>("Date").HasColumnType("datetime(6)");
                b.Property<decimal>("OpeningBalance").HasColumnType("decimal(10,2)");
                b.Property<decimal?>("ClosingBalance").HasColumnType("decimal(10,2)");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<string>("OpenedBy").IsRequired().HasMaxLength(256).HasColumnType("varchar(256)");
                b.Property<string>("ClosedBy").HasMaxLength(256).HasColumnType("varchar(256)");
                b.Property<DateTime>("OpenedAt").HasColumnType("datetime(6)");
                b.Property<DateTime?>("ClosedAt").HasColumnType("datetime(6)");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("varchar(500)");
                b.HasKey("Id");
                b.HasIndex("Date").IsUnique();
                b.ToTable("CashRegisters");
            });

            // ── MemberPlans ───────────────────────────────────────────────────────
            modelBuilder.Entity("FitManager.Models.MemberPlan", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("MemberId").HasColumnType("int");
                b.Property<int>("PlanId").HasColumnType("int");
                b.Property<int?>("PaymentId").HasColumnType("int");
                b.Property<DateTime>("StartDate").HasColumnType("datetime(6)");
                b.Property<DateTime>("EndDate").HasColumnType("datetime(6)");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<string>("Notes").HasMaxLength(300).HasColumnType("varchar(300)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.HasKey("Id");
                b.HasIndex("MemberId");
                b.HasIndex("PlanId");
                b.HasIndex("PaymentId");
                b.ToTable("MemberPlans");
            });

            // ── Payments ──────────────────────────────────────────────────────────
            modelBuilder.Entity("FitManager.Models.Payment", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<decimal>("Amount").HasColumnType("decimal(10,2)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("CreatedBy").HasColumnType("longtext");
                b.Property<string>("Description").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<DateTime>("DueDate").HasColumnType("datetime(6)");
                b.Property<int>("MemberId").HasColumnType("int");
                b.Property<int?>("PlanId").HasColumnType("int");
                b.Property<int?>("MemberPlanId").HasColumnType("int");
                b.Property<int?>("CashRegisterId").HasColumnType("int");
                b.Property<int>("Method").HasColumnType("int");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<DateTime>("PaymentDate").HasColumnType("datetime(6)");
                b.Property<string>("ReceiptNumber").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int>("Status").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("MemberId");
                b.HasIndex("PlanId");
                b.HasIndex("MemberPlanId");
                b.HasIndex("CashRegisterId");
                b.ToTable("Payments");
            });

            // ── CashTransactions ──────────────────────────────────────────────────
            modelBuilder.Entity("FitManager.Models.CashTransaction", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("CashRegisterId").HasColumnType("int");
                b.Property<int>("Type").HasColumnType("int");
                b.Property<decimal>("Amount").HasColumnType("decimal(10,2)");
                b.Property<string>("Description").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<int?>("Method").HasColumnType("int");
                b.Property<string>("Notes").HasMaxLength(300).HasColumnType("varchar(300)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("CreatedBy").IsRequired().HasMaxLength(256).HasColumnType("varchar(256)");
                b.HasKey("Id");
                b.HasIndex("CashRegisterId");
                b.ToTable("CashTransactions");
            });

            // ── MenuItems ─────────────────────────────────────────────────────────
            modelBuilder.Entity("FitManager.Models.MenuItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Action").HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<string>("Controller").HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<string>("Icon").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<bool>("IsActive").HasColumnType("tinyint(1)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int>("OrderIndex").HasColumnType("int");
                b.Property<int?>("ParentId").HasColumnType("int");
                b.Property<string>("Url").HasMaxLength(200).HasColumnType("varchar(200)");
                b.HasKey("Id");
                b.HasIndex("ParentId");
                b.ToTable("MenuItems");
            });

            // ── RoleMenuPermissions ───────────────────────────────────────────────
            modelBuilder.Entity("FitManager.Models.RoleMenuPermission", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<bool>("IsEnabled").HasColumnType("tinyint(1)");
                b.Property<int>("MenuItemId").HasColumnType("int");
                b.Property<string>("RoleId").IsRequired().HasColumnType("varchar(255)");
                b.HasKey("Id");
                b.HasIndex("MenuItemId");
                b.HasIndex("RoleId", "MenuItemId").IsUnique();
                b.ToTable("RoleMenuPermissions");
            });

            // ── Relationships ─────────────────────────────────────────────────────
            modelBuilder.Entity("FitManager.Models.Payment", b =>
            {
                b.HasOne("FitManager.Models.Member", "Member")
                    .WithMany("Payments")
                    .HasForeignKey("MemberId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("FitManager.Models.Plan", "Plan")
                    .WithMany("Payments")
                    .HasForeignKey("PlanId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.HasOne("FitManager.Models.MemberPlan", "MemberPlan")
                    .WithMany()
                    .HasForeignKey("MemberPlanId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.HasOne("FitManager.Models.CashRegister", "CashRegister")
                    .WithMany("Payments")
                    .HasForeignKey("CashRegisterId")
                    .OnDelete(DeleteBehavior.SetNull);
            });

            modelBuilder.Entity("FitManager.Models.MemberPlan", b =>
            {
                b.HasOne("FitManager.Models.Member", "Member")
                    .WithMany()
                    .HasForeignKey("MemberId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("FitManager.Models.Plan", "Plan")
                    .WithMany("MemberPlans")
                    .HasForeignKey("PlanId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("FitManager.Models.Payment", "Payment")
                    .WithMany()
                    .HasForeignKey("PaymentId")
                    .OnDelete(DeleteBehavior.SetNull);
            });

            modelBuilder.Entity("FitManager.Models.CashTransaction", b =>
            {
                b.HasOne("FitManager.Models.CashRegister", "CashRegister")
                    .WithMany("Transactions")
                    .HasForeignKey("CashRegisterId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("FitManager.Models.MenuItem", b =>
            {
                b.HasOne("FitManager.Models.MenuItem", "Parent")
                    .WithMany("Children")
                    .HasForeignKey("ParentId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("FitManager.Models.RoleMenuPermission", b =>
            {
                b.HasOne("FitManager.Models.ApplicationRole", "Role")
                    .WithMany("MenuPermissions")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("FitManager.Models.MenuItem", "MenuItem")
                    .WithMany("RolePermissions")
                    .HasForeignKey("MenuItemId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
