// <auto-generated />
using System;
using FitManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FitManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260101000000_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FitManager.Models.ApplicationRole", b =>
            {
                b.Property<string>("Id").HasColumnType("varchar(255)");
                b.Property<string>("ConcurrencyStamp").HasColumnType("longtext");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("Description").HasColumnType("longtext");
                b.Property<bool>("IsSystem").HasColumnType("tinyint(1)");
                b.Property<string>("Name").HasMaxLength(256).HasColumnType("varchar(256)");
                b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("varchar(256)");
                b.HasKey("Id");
                b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex");
                b.ToTable("Roles");
            });

            modelBuilder.Entity("FitManager.Models.ApplicationUser", b =>
            {
                b.Property<string>("Id").HasColumnType("varchar(255)");
                b.Property<int>("AccessFailedCount").HasColumnType("int");
                b.Property<string>("ConcurrencyStamp").HasColumnType("longtext");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("Email").HasMaxLength(256).HasColumnType("varchar(256)");
                b.Property<bool>("EmailConfirmed").HasColumnType("tinyint(1)");
                b.Property<string>("FirstName").IsRequired().HasColumnType("longtext");
                b.Property<bool>("IsActive").HasColumnType("tinyint(1)");
                b.Property<DateTime?>("LastLoginAt").HasColumnType("datetime(6)");
                b.Property<string>("LastName").IsRequired().HasColumnType("longtext");
                b.Property<bool>("LockoutEnabled").HasColumnType("tinyint(1)");
                b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("datetime(6)");
                b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("varchar(256)");
                b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("varchar(256)");
                b.Property<string>("PasswordHash").HasColumnType("longtext");
                b.Property<string>("PhoneNumber").HasColumnType("longtext");
                b.Property<bool>("PhoneNumberConfirmed").HasColumnType("tinyint(1)");
                b.Property<string>("PhotoPath").HasColumnType("longtext");
                b.Property<string>("SecurityStamp").HasColumnType("longtext");
                b.Property<bool>("TwoFactorEnabled").HasColumnType("tinyint(1)");
                b.Property<string>("UserName").HasMaxLength(256).HasColumnType("varchar(256)");
                b.HasKey("Id");
                b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex");
                b.ToTable("Users");
            });

            modelBuilder.Entity("FitManager.Models.Member", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Address").HasMaxLength(300).HasColumnType("varchar(300)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("DNI").HasMaxLength(20).HasColumnType("varchar(20)");
                b.Property<DateTime?>("DateOfBirth").HasColumnType("datetime(6)");
                b.Property<string>("Email").HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("MemberNumber").IsRequired().HasMaxLength(20).HasColumnType("varchar(20)");
                b.Property<DateTime?>("MembershipEndDate").HasColumnType("datetime(6)");
                b.Property<DateTime>("MembershipStartDate").HasColumnType("datetime(6)");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("Phone").HasMaxLength(30).HasColumnType("varchar(30)");
                b.Property<string>("PhotoPath").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime(6)");
                b.HasKey("Id");
                b.HasIndex("DNI");
                b.HasIndex("MemberNumber").IsUnique();
                b.ToTable("Members");
            });

            modelBuilder.Entity("FitManager.Models.MenuItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Action").HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<string>("Controller").HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<string>("Icon").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<bool>("IsActive").HasColumnType("tinyint(1)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int>("OrderIndex").HasColumnType("int");
                b.Property<int?>("ParentId").HasColumnType("int");
                b.Property<string>("Url").HasMaxLength(200).HasColumnType("varchar(200)");
                b.HasKey("Id");
                b.HasIndex("ParentId");
                b.ToTable("MenuItems");
            });

            modelBuilder.Entity("FitManager.Models.Payment", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<decimal>("Amount").HasColumnType("decimal(10,2)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("CreatedBy").HasColumnType("longtext");
                b.Property<string>("Description").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<DateTime>("DueDate").HasColumnType("datetime(6)");
                b.Property<int>("MemberId").HasColumnType("int");
                b.Property<int>("Method").HasColumnType("int");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<DateTime>("PaymentDate").HasColumnType("datetime(6)");
                b.Property<string>("ReceiptNumber").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int>("Status").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("MemberId");
                b.ToTable("Payments");
            });

            modelBuilder.Entity("FitManager.Models.RoleMenuPermission", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<bool>("IsEnabled").HasColumnType("tinyint(1)");
                b.Property<int>("MenuItemId").HasColumnType("int");
                b.Property<string>("RoleId").IsRequired().HasColumnType("varchar(255)");
                b.HasKey("Id");
                b.HasIndex("MenuItemId");
                b.HasIndex("RoleId", "MenuItemId").IsUnique();
                b.ToTable("RoleMenuPermissions");
            });

            modelBuilder.Entity("FitManager.Models.Payment", b =>
            {
                b.HasOne("FitManager.Models.Member", "Member")
                    .WithMany("Payments")
                    .HasForeignKey("MemberId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Member");
            });

            modelBuilder.Entity("FitManager.Models.MenuItem", b =>
            {
                b.HasOne("FitManager.Models.MenuItem", "Parent")
                    .WithMany("Children")
                    .HasForeignKey("ParentId")
                    .OnDelete(DeleteBehavior.Restrict);
                b.Navigation("Parent");
            });

            modelBuilder.Entity("FitManager.Models.RoleMenuPermission", b =>
            {
                b.HasOne("FitManager.Models.ApplicationRole", "Role")
                    .WithMany("MenuPermissions")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("FitManager.Models.MenuItem", "MenuItem")
                    .WithMany("RolePermissions")
                    .HasForeignKey("MenuItemId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("MenuItem");
                b.Navigation("Role");
            });

            modelBuilder.Entity("FitManager.Models.Member", b => { b.Navigation("Payments"); });
            modelBuilder.Entity("FitManager.Models.MenuItem", b => { b.Navigation("Children"); b.Navigation("RolePermissions"); });
            modelBuilder.Entity("FitManager.Models.ApplicationRole", b => { b.Navigation("MenuPermissions"); });
#pragma warning restore 612, 618
        }
    }
}
