// <auto-generated />
using System;
using FitManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FitManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260423010000_AddRoutinesModule")]
    partial class AddRoutinesModule
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FitManager.Models.Exercise", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("varchar(120)");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<int>("MuscleGroup").HasColumnType("int");
                b.Property<int>("ExerciseType").HasColumnType("int");
                b.Property<bool>("IsCustom").HasColumnType("tinyint(1)");
                b.Property<bool>("IsActive").HasColumnType("tinyint(1)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.HasKey("Id");
                b.ToTable("Exercises");
            });

            modelBuilder.Entity("FitManager.Models.Routine", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Name").IsRequired().HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<int>("Goal").HasColumnType("int");
                b.Property<int>("DurationWeeks").HasColumnType("int");
                b.Property<int>("FrequencyPerWeek").HasColumnType("int");
                b.Property<bool>("IsGeneral").HasColumnType("tinyint(1)");
                b.Property<bool>("IsActive").HasColumnType("tinyint(1)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("CreatedBy").HasMaxLength(256).HasColumnType("varchar(256)");
                b.HasKey("Id");
                b.ToTable("Routines");
            });

            modelBuilder.Entity("FitManager.Models.RoutineDay", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("RoutineId").HasColumnType("int");
                b.Property<int>("DayNumber").HasColumnType("int");
                b.Property<string>("Name").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<bool>("IsRestDay").HasColumnType("tinyint(1)");
                b.Property<int>("OrderIndex").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("RoutineId");
                b.ToTable("RoutineDays");
            });

            modelBuilder.Entity("FitManager.Models.RoutineExercise", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("RoutineDayId").HasColumnType("int");
                b.Property<int>("ExerciseId").HasColumnType("int");
                b.Property<int>("Sets").HasColumnType("int");
                b.Property<string>("Reps").IsRequired().HasMaxLength(30).HasColumnType("varchar(30)");
                b.Property<decimal?>("Weight").HasColumnType("decimal(8,2)");
                b.Property<int?>("RestSeconds").HasColumnType("int");
                b.Property<string>("Notes").HasMaxLength(300).HasColumnType("varchar(300)");
                b.Property<int>("OrderIndex").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("RoutineDayId");
                b.HasIndex("ExerciseId");
                b.ToTable("RoutineExercises");
            });

            modelBuilder.Entity("FitManager.Models.MemberRoutine", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("MemberId").HasColumnType("int");
                b.Property<int>("RoutineId").HasColumnType("int");
                b.Property<DateTime>("AssignedAt").HasColumnType("datetime(6)");
                b.Property<DateTime>("StartDate").HasColumnType("datetime(6)");
                b.Property<DateTime?>("EndDate").HasColumnType("datetime(6)");
                b.Property<bool>("IsActive").HasColumnType("tinyint(1)");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("AssignedBy").HasMaxLength(256).HasColumnType("varchar(256)");
                b.HasKey("Id");
                b.ToTable("MemberRoutines");
            });
#pragma warning restore 612, 618
        }
    }
}
