// <auto-generated />
using FitManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FitManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260424000000_AddNutritionModule")]
    partial class AddNutritionModule
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
